---

version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8889:80"
    volumes:
      - ./volumes/nginx/conf.d/app2.conf:/etc/nginx/conf.d/default.conf

  app2:
    image: node:slim
    command: node /app/app.js
    expose:
      - 9001
    volumes:
      - ./app2:/app
    networks:
      default:
        aliases:
          - app2.dev
