---

version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - ./volumes/nginx/conf.d/app1.conf:/etc/nginx/conf.d/default.conf

  app1:
    image: php:5-fpm-alpine
    expose:
      - 9000
    volumes:
      - ./app1:/var/www/html/app1
    networks:
      default:
        aliases:
          - app1.dev

  app2_nginx:
    extends:
      file: ./docker-compose-app2.yml
      service: nginx
    # Override port from extended service.
    # In this case, /app2/ will still be available on port 8889.
    ports:
      - "8890:80"

  # Explicitly include app2. nginx cannot depend on app2 using "depends_on" or "links"
  # because it is also being extended.
  app2:
    extends:
      file: ./docker-compose-app2.yml
      service: app2
